### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Tidalwave_Interface)
add_subdirectory(Tidalwave_InterfaceContent)
add_subdirectory(Backend)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Tidalwave_Interfaceplugin
    Tidalwave_InterfaceContentplugin
    QtQuickDesignerComponents)