// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Tidalwave_Interface();
Q_GHS_KEEP_REFERENCE(qml_register_types_Tidalwave_Interface)

class Tidalwave_InterfacePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Tidalwave_InterfacePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Tidalwave_Interface;
        Q_UNUSED(registration)
    }
};



#include "Tidalwave_Interfaceplugin_Tidalwave_InterfacePlugin.moc"
