// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Tidalwave_InterfaceContent();
Q_GHS_KEEP_REFERENCE(qml_register_types_Tidalwave_InterfaceContent)

class Tidalwave_InterfaceContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Tidalwave_InterfaceContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Tidalwave_InterfaceContent;
        Q_UNUSED(registration)
    }
};



#include "Tidalwave_InterfaceContentplugin_Tidalwave_InterfaceContentPlugin.moc"
